name: type_text
description: A simple flutter widget that writes your texts like a typewriter.
version: 1.0.5
homepage: https://github.com/Descrout/type_text.git

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: